# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 13:52


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, help_text='Date the Record was processed.', null=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'ordering': ['date_of_entry', 'contact_form'],
                'verbose_name': 'Contact Record',
                'verbose_name_plural': 'Contact Records',
            },
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('fieldType', models.CharField(choices=[(b'CharField', b'CharField'), (b'BooleanField', b'BooleanField'), (b'EmailField', b'EmailField'), (b'DecimalField', b'DecimalField'), (b'FloatField', b'FloatField'), (b'IntegerField', b'IntegerField'), (b'FileField', b'FileField'), (b'ImageField', b'ImageField'), (b'IPAddressField', b'IPAddressField'), (b'MathCaptcha', b'Math Captcha'), (b'auto_Textarea', 'CharField as Textarea'), (b'auto_hidden_input', 'CharField as HiddenInput'), (b'auto_referral_page', 'Referral page as HiddenInput'), (b'auto_GET_parameter', 'GET parameter as HiddenInput'), (b'CharFieldWithValidator', b'CharFieldWithValidator'), (b'ReCaptcha', b'reCAPTCHA')], max_length=100)),
                ('initial', models.CharField(blank=True, max_length=250, null=True, verbose_name='Inital Value')),
                ('required', models.BooleanField(default=True, verbose_name='Mandatory field')),
                ('widget', models.CharField(blank=True, help_text='Will be ignored in the current version.', max_length=250, null=True, verbose_name='Widget')),
                ('inline_ordering_position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('inline_ordering_position',),
            },
        ),
        migrations.CreateModel(
            name='RemoteForm',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_remote_form_remoteform', serialize=False, to='cms.CMSPlugin')),
                ('post_url', models.CharField(default=b'#remoteURL', max_length=200, null=True, verbose_name='Remote URL')),
                ('submit_button_text', models.CharField(blank=True, max_length=30, verbose_name='Text for the Submit button.')),
                ('thanks', models.TextField(verbose_name='Message displayed after submitting the contact form.')),
                ('thanks_in_modal', models.BooleanField(default=True, verbose_name='Show Thanks In Modal')),
                ('collect_records', models.BooleanField(default=True, help_text='If active, all records for this Form will be stored in the Database.', verbose_name='Collect Records')),
                ('template', models.CharField(choices=[(b'cmsplugin_remote_form/default.html', b'default.html'), (b'cmsplugin_remote_form/inline.html', b'inline.html')], default=b'cmsplugin_remote_form/default.html', max_length=255)),
                ('fields_in_row', models.BooleanField(default=False, verbose_name='Put Fields in a .row')),
                ('field_class', models.CharField(blank=True, max_length=50, verbose_name='CSS class to put on the field.')),
                ('label_class', models.CharField(blank=True, max_length=50, verbose_name='CSS class to put on the label.')),
            ],
            options={
                'verbose_name': 'Remote Form',
                'verbose_name_plural': 'Remote Forms',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsplugin_remote_form.RemoteForm', verbose_name='Contact Form'),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='contact_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsplugin_remote_form.RemoteForm', verbose_name='Contact Form'),
        ),
    ]
