# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_remote_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteform',
            name='field_class',
        ),
        migrations.RemoveField(
            model_name='remoteform',
            name='fields_in_row',
        ),
        migrations.RemoveField(
            model_name='remoteform',
            name='label_class',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='css_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='fieldType',
            field=models.CharField(choices=[(b'CharField', b'CharField'), (b'BooleanField', b'BooleanField'), (b'EmailField', b'EmailField'), (b'DecimalField', b'DecimalField'), (b'FloatField', b'FloatField'), (b'IntegerField', b'IntegerField'), (b'FileField', b'FileField'), (b'ImageField', b'ImageField'), (b'USStateSelect', b'US State Selector'), (b'IPAddressField', b'IPAddressField'), (b'MathCaptcha', b'Math Captcha'), (b'auto_Textarea', 'CharField as Textarea'), (b'auto_hidden_input', 'CharField as HiddenInput'), (b'auto_referral_page', 'Referral page as HiddenInput'), (b'auto_GET_parameter', 'GET parameter as HiddenInput'), (b'CharFieldWithValidator', b'CharFieldWithValidator'), (b'ReCaptcha', b'reCAPTCHA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='remoteform',
            name='template',
            field=models.CharField(default=b'cmsplugin_remote_form/default.html', max_length=255),
        ),
    ]
