# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 20:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_remote_form', '0002_auto_20170421_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteform',
            name='on_submit',
            field=models.CharField(blank=True, help_text=b'Google Analytics Code', max_length=400, null=True),
        ),
    ]
