# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 20:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_remote_form', '0003_remoteform_on_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteform',
            name='notification_emails',
            field=models.CharField(blank=True, help_text='multiple emails separated by commas', max_length=250, null=True, verbose_name='Email Records To:'),
        ),
    ]
