# Generated by Django 2.2.12 on 2020-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_remote_form', '0004_remoteform_notification_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='fieldType',
            field=models.CharField(choices=[('CharField', 'CharField'), ('BooleanField', 'BooleanField'), ('EmailField', 'EmailField'), ('DecimalField', 'DecimalField'), ('FloatField', 'FloatField'), ('IntegerField', 'IntegerField'), ('FileField', 'FileField'), ('ImageField', 'ImageField'), ('USStateSelect', 'US State Selector'), ('IPAddressField', 'IPAddressField'), ('MathCaptcha', 'Math Captcha'), ('auto_Textarea', 'CharField as Textarea'), ('auto_hidden_input', 'CharField as HiddenInput'), ('auto_referral_page', 'Referral page as HiddenInput'), ('auto_GET_parameter', 'GET parameter as HiddenInput'), ('CharFieldWithValidator', 'CharFieldWithValidator'), ('ChoiceField', 'ChoiceField'), ('ReCaptcha', 'reCAPTCHA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='initial',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='remoteform',
            name='error_notification_emails',
            field=models.CharField(blank=True, help_text='multiple emails separated by commas', max_length=250, null=True, verbose_name='Email Errors To:'),
        ),
        migrations.AlterField(
            model_name='remoteform',
            name='on_submit',
            field=models.CharField(blank=True, help_text='Google Analytics Code', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='remoteform',
            name='post_url',
            field=models.CharField(default='#remoteURL', max_length=200, null=True, verbose_name='Remote URL'),
        ),
        migrations.AlterField(
            model_name='remoteform',
            name='template',
            field=models.CharField(choices=[('cmsplugin_remote_form_templates/default.html', 'Default'), ('cmsplugin_remote_form_templates/vertical_onecol.html', 'Vertical - One Col')], default='cmsplugin_remote_form/default.html', max_length=255),
        ),
    ]
