# Generated by Django 2.2.12 on 2020-05-04 14:04

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cmsplugin_remote_form', '0005_auto_20200429_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteform',
            name='link_parameter',
            field=models.CharField(default='', help_text='Adds a custom parameter onto the thanks page link', max_length=255),
        ),
        migrations.AddField(
            model_name='remoteform',
            name='thanks_page',
            field=cms.models.fields.PageField(blank=True, help_text='Page to display after submitting the contact form', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='remoteform',
            name='template',
            field=models.CharField(choices=[('cmsplugin_remote_form_templates/default.html', 'Default - Label Inline'), ('cmsplugin_remote_form_templates/vertical_onecol.html', 'Vertical - One Col')], default='cmsplugin_remote_form/default.html', max_length=255),
        ),
    ]
