# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    try:
        contact_forms = apps.get_model('cmsplugin_contact_plus', 'ContactPlus')
        contact_forms.objects.all().update(template="cmsplugin_contact_plus/default.html")
    except Exception:
        return


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0004_auto_20170301_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactplus',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='contactplus',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='contactplus',
            name='title',
        ),
        migrations.AddField(
            model_name='contactplus',
            name='field_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='CSS class to put on the field.'),
        ),
        migrations.AddField(
            model_name='contactplus',
            name='fields_in_row',
            field=models.BooleanField(default=False, verbose_name='Put Fields in a .row'),
        ),
        migrations.AddField(
            model_name='contactplus',
            name='label_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='CSS class to put on the label.'),
        ),
        migrations.AddField(
            model_name='contactplus',
            name='post_url',
            field=models.CharField(default=b'#remoteURL', max_length=200, null=True, verbose_name='Remote URL'),
        ),
        migrations.AddField(
            model_name='contactplus',
            name='thanks_in_modal',
            field=models.BooleanField(default=True, verbose_name='Show Thanks In Modal'),
        ),
        migrations.AlterField(
            model_name='contactplus',
            name='template',
            field=models.CharField(choices=[(b'cmsplugin_contact_plus/base.html', b'base.html'), (b'cmsplugin_contact_plus/change_form.html', b'change_form.html'), (b'cmsplugin_contact_plus/default.html', b'default.html'), (b'cmsplugin_contact_plus/inline.html', b'inline.html')], default=b'cmsplugin_contact_plus/default.html', max_length=255),
        ),
        migrations.RunPython(forwards)
    ]
